/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jrat_plugin_recovery_stub_NativeUtils */

#ifndef _Included_jrat_plugin_recovery_stub_NativeUtils
#define _Included_jrat_plugin_recovery_stub_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jrat_plugin_recovery_stub_NativeUtils
 * Method:    cryptUnprotectData
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jrat_plugin_recovery_stub_NativeUtils_cryptUnprotectData
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
